-- CREACION DE TABLAS DE VIAJES AVENTURA

-- 1. Tabla de Tipos de Usuarios
CREATE TABLE tipos_usuarios (
    id_tipo_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(100) NOT NULL
);

-- 2. Tabla de Usuarios
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(200) NOT NULL,
    apellido_paterno VARCHAR2(200) NOT NULL,
    apellido_materno VARCHAR2(200),
    rut VARCHAR2(30) UNIQUE,
    fecha_nacimiento DATE,
    correo_electronico VARCHAR2(255) NOT NULL UNIQUE,
    telefono VARCHAR2(30),
    id_tipo_usuario NUMBER,
    estado NUMBER(1) DEFAULT 1, -- 1 si esta Activo, 0 Inactivo
    password VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_tipo_usuario FOREIGN KEY (id_tipo_usuario) REFERENCES tipos_usuarios(id_tipo_usuario)
);

-- 3. Tabla de Destinos
CREATE TABLE destinos (
    id_destino NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_destino VARCHAR2(255) NOT NULL,
    pais VARCHAR2(100),
    ciudad VARCHAR2(100),
    descripcion CLOB,
    actividades VARCHAR2(255),
    precio NUMBER(12) NOT NULL
);

-- 4. Tabla de Paquetes
CREATE TABLE paquetes (
    id_paquete NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_paquete VARCHAR2(255) NOT NULL,
    precio_total NUMBER(12),
    duracion_dias NUMBER,
    servicios_incluidos VARCHAR2(255),
    fecha_inicio DATE,
    fecha_regreso DATE
);

-- 5. Tabla Intermedia destinos-paquetes
CREATE TABLE destinos_paquetes (
    destinos_paquete_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paquete NUMBER NOT NULL,
    id_destino NUMBER NOT NULL,
    CONSTRAINT fk_dp_paquete FOREIGN KEY (id_paquete) REFERENCES paquetes(id_paquete),
    CONSTRAINT fk_dp_destino FOREIGN KEY (id_destino) REFERENCES destinos(id_destino)
);

-- 6. Tabla de Reservaciones
CREATE TABLE reservaciones (
    id_reservacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paquete NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- fecha ahora
    estado_reservacion NUMBER(1) DEFAULT 1, -- 1: pendiente, 2: pagada, 0: cancelada
    CONSTRAINT fk_res_paquete FOREIGN KEY (id_paquete) REFERENCES paquetes(id_paquete),
    CONSTRAINT fk_res_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);


-- INSERTAR TIPOS DE USUARIO
INSERT INTO tipos_usuarios (id_tipo_usuario,tipo) VALUES (1,'Cliente');
INSERT INTO tipos_usuarios (id_tipo_usuario,tipo) VALUES (2,'Trabajador');
INSERT INTO tipos_usuarios (id_tipo_usuario,tipo) VALUES (3,'Administrador');


COMMIT;


